language: go
go:
  - 1.13.x

sudo: required

services:
  - docker

before_install:
  - make install.tools

install: true

script:
  - echo "${TRAVIS_COMMIT_RANGE} -> ${TRAVIS_COMMIT_RANGE/.../..} (travis-ci/travis-ci#4596)"
  - TRAVIS_COMMIT_RANGE="${TRAVIS_COMMIT_RANGE/.../..}" make .gitvalidation
  - make docs conformance
